insert into public.events (
  title,
  slug,
  description,
  start_datetime,
  end_datetime,
  region,
  secondary_regions,
  venue_name,
  address,
  speaker_names,
  category,
  gender_audience,
  age_group,
  registration_url,
  flyer_image_url,
  contact_name,
  contact_email,
  tags,
  status
)
values
(
  'Friday Halaqa: Anchored Hearts',
  'friday-halaqa-anchored-hearts',
  'A weekly Friday night halaqa focused on sincerity, consistency, and staying rooted in the masjid community.',
  now() + interval '2 days' + interval '19 hours',
  now() + interval '2 days' + interval '21 hours',
  'YM Sharon',
  array['YM MetroWest'],
  'ICNE Sharon',
  '1515 Washington St, Sharon, MA',
  array['Ustadh Kareem Ahmed'],
  'Halaqa',
  'Co-ed',
  'High School + College',
  'https://forms.gle/example-sharon-halaqa',
  'https://images.unsplash.com/photo-1517486808906-6ca8b3f04846?auto=format&fit=crop&w=1200&q=80',
  'Br. Hasan',
  'sharon@ymne.org',
  array['Halaqa', 'Education', 'Youth Night'],
  'published'
),
(
  'Qiyam Night: Hope & Dua',
  'qiyam-night-hope-dua',
  'Late-night worship, reminders, qiyam, and breakfast for youth from across the region.',
  now() + interval '9 days' + interval '22 hours',
  now() + interval '10 days' + interval '5 hours',
  'YM Pawtucket',
  array['YM Sharon', 'YM Worcester (WIC)'],
  'Masjid Ar-Razzaq',
  '727 East Ave, Pawtucket, RI',
  array['Sh. Ibrahim Saad'],
  'Qiyam',
  'Brothers',
  'High School + College',
  'https://forms.gle/example-qiyam',
  'https://images.unsplash.com/photo-1519817650390-64a93db511aa?auto=format&fit=crop&w=1200&q=80',
  'Br. Yusuf',
  'pawtucket@ymne.org',
  array['Qiyam', 'Brothers', 'Youth Night'],
  'published'
),
(
  'Sisters Tea & Reflection Circle',
  'sisters-tea-reflection-circle',
  'An uplifting sisters-only gathering with tea, discussion, and guided reflection on gratitude and sisterhood.',
  now() + interval '13 days' + interval '15 hours',
  now() + interval '13 days' + interval '17 hours',
  'YM MetroWest',
  array['YM Sharon'],
  'Community Hall',
  '12 Green St, Framingham, MA',
  array['Sr. Noura Hasan'],
  'Social',
  'Sisters',
  'Young Adults',
  'https://forms.gle/example-sisters-tea',
  'https://images.unsplash.com/photo-1495474472287-4d71bcdd2085?auto=format&fit=crop&w=1200&q=80',
  'Sr. Mariam',
  'metrowest@ymne.org',
  array['Sisters', 'Social', 'Education'],
  'published'
),
(
  'Basketball Night',
  'basketball-night-lowell',
  'Open gym, team rotations, and a short reminder before play begins.',
  now() + interval '16 days' + interval '18 hours',
  now() + interval '16 days' + interval '21 hours',
  'YM Lowell',
  array[]::text[],
  'Lowell YMCA Gym',
  '35 YMCA Dr, Lowell, MA',
  array['Br. Samir Ali'],
  'Sports',
  'Brothers',
  'Teens',
  'https://forms.gle/example-basketball',
  'https://images.unsplash.com/photo-1546519638-68e109498ffc?auto=format&fit=crop&w=1200&q=80',
  'Br. Omar',
  'lowell@ymne.org',
  array['Sports', 'Brothers', 'Youth Night'],
  'published'
),
(
  'Seerah Series: Mercy in Leadership',
  'seerah-series-mercy-in-leadership',
  'Part of an ongoing Seerah series looking at prophetic leadership and compassion in community building.',
  now() + interval '20 days' + interval '18 hours',
  now() + interval '20 days' + interval '20 hours',
  'YM Worcester (WIC)',
  array['YM MetroWest'],
  'WIC Youth Hall',
  '248 East Mountain St, Worcester, MA',
  array['Ustadh Haseeb Khan'],
  'Education',
  'Co-ed',
  'College + Young Professionals',
  'https://forms.gle/example-seerah',
  'https://images.unsplash.com/photo-1517048676732-d65bc937f952?auto=format&fit=crop&w=1200&q=80',
  'Br. Bilal',
  'worcester@ymne.org',
  array['Education', 'Halaqa', 'Family'],
  'published'
),
(
  'Community Service Day',
  'community-service-day',
  'Serve local neighbors together through a food pantry support project and neighborhood cleanup.',
  now() + interval '26 days' + interval '10 hours',
  now() + interval '26 days' + interval '14 hours',
  'YM Pawtucket',
  array['YM Sharon', 'YM Lowell'],
  'RI Community Center',
  '1 Hope St, Providence, RI',
  array['Br. Zayd Noor'],
  'Volunteer',
  'Co-ed',
  'All Ages',
  'https://forms.gle/example-service-day',
  'https://images.unsplash.com/photo-1559027615-cd4628902d4a?auto=format&fit=crop&w=1200&q=80',
  'Sr. Amina',
  'service@ymne.org',
  array['Volunteer', 'Family', 'Youth Night'],
  'published'
),
(
  'Guest Speaker Night: Faith in College',
  'guest-speaker-night-faith-in-college',
  'A practical session for students navigating campus life, friendships, and spiritual consistency.',
  now() + interval '34 days' + interval '18 hours',
  now() + interval '34 days' + interval '20 hours',
  'YM Sharon',
  array['YM Lowell', 'YM MetroWest'],
  'Masjid Youth Lounge',
  '1515 Washington St, Sharon, MA',
  array['Dr. Layth Siddiqi'],
  'Conference',
  'Co-ed',
  'College',
  'https://forms.gle/example-college-talk',
  'https://images.unsplash.com/photo-1516321318423-f06f85e504b3?auto=format&fit=crop&w=1200&q=80',
  'Sr. Huda',
  'events@ymne.org',
  array['Conference', 'Education', 'Youth Night'],
  'published'
),
(
  'Youth Night Bonfire',
  'youth-night-bonfire',
  'A relaxed community night with reminders, snacks, team games, and space for new attendees to connect.',
  now() + interval '42 days' + interval '19 hours',
  now() + interval '42 days' + interval '22 hours',
  'YM MetroWest',
  array['YM Worcester (WIC)'],
  'Camp Cedar Grounds',
  '85 Forest Path, Hopkinton, MA',
  array['Br. Hamza Usman'],
  'Youth Night',
  'Co-ed',
  'Teens + Young Adults',
  'https://forms.gle/example-bonfire',
  'https://images.unsplash.com/photo-1500530855697-b586d89ba3ee?auto=format&fit=crop&w=1200&q=80',
  'Br. Kareem',
  'bonfire@ymne.org',
  array['Youth Night', 'Social', 'Family'],
  'published'
),
(
  'Tafsir Circle: Surah Al-Kahf',
  'tafsir-circle-surah-al-kahf',
  'Monthly tafsir circle with guided notes and discussion prompts for youth reflection.',
  now() + interval '54 days' + interval '17 hours',
  now() + interval '54 days' + interval '19 hours',
  'YM Worcester (WIC)',
  array['YM Pawtucket'],
  'WIC Library Room',
  '248 East Mountain St, Worcester, MA',
  array['Ustadha Sarah Omar'],
  'Education',
  'Sisters',
  'High School + College',
  'https://forms.gle/example-tafsir',
  'https://images.unsplash.com/photo-1504052434569-70ad5836ab65?auto=format&fit=crop&w=1200&q=80',
  'Sr. Noor',
  'tafsir@ymne.org',
  array['Education', 'Sisters', 'Halaqa'],
  'published'
),
(
  'Regional Fundraiser Planning Meeting',
  'regional-fundraiser-planning-meeting',
  'Internal working session for leaders organizing a summer fundraiser and volunteer roles.',
  now() + interval '61 days' + interval '18 hours',
  now() + interval '61 days' + interval '19 hours 30 minutes',
  'YM Lowell',
  array['YM Sharon', 'YM Pawtucket', 'YM MetroWest', 'YM Worcester (WIC)'],
  'Zoom',
  'Online',
  array['Regional Shura Team'],
  'Fundraiser',
  'Co-ed',
  'Leadership',
  null,
  null,
  'Regional Office',
  'regional@ymne.org',
  array['Fundraiser', 'Volunteer'],
  'draft'
);
